# This is a basic workflow to update the leaderboard
name: Update Leaderboard

on:
  schedule:
    # Run every 3 hours
    - cron:  '0 0 * * *'
  issue_comment:
    types: [created, edited]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to v3
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret here
        run: python .github/scripts/update_readme.py